"""
    setup_artifact_overrides(runfiles_dir, include_paths)

Scan runfiles for JLL artifact metadata and create Overrides.toml for artifact discovery.

JLL packages reference binary artifacts by their git-tree-sha1 content hash. Julia's
artifact system looks for these in the depot's artifacts/ directory. When running in
Bazel's sandbox, artifacts are downloaded by Bazel and placed in runfiles, but Julia
doesn't know to look there.

This function:
1. Scans runfiles for _jll_artifact_meta.json files (generated by Bazel for each artifact)
2. Extracts the git-tree-sha1 content hash and the actual path to the artifact
3. Writes an Overrides.toml to the depot that maps each hash to its runfiles location

The Overrides.toml format is:
```toml
[<git-tree-sha1>]
<artifact_name> = "<absolute_path_to_artifact>"
```

But for simpler artifacts we can just use:
```toml
<git-tree-sha1> = "<absolute_path_to_artifact>"
```
"""
function setup_artifact_overrides(runfiles_dir::String, include_paths::Vector{String})
    @debug "Setting up artifact overrides from runfiles"

    # Collect all artifact metadata files from runfiles
    artifact_overrides = Dict{String,String}()  # git_tree_sha1 => path

    # Walk through include paths looking for _jll_artifact_meta.json files
    # These are placed in artifact directories by our Bazel BUILD generation
    for inc_path in include_paths
        parent_dir = dirname(inc_path)
        search_dirs = [parent_dir, inc_path]

        for search_dir in search_dirs
            if !isdir(search_dir)
                continue
            end

            # Recursively find all _jll_artifact_meta.json files
            for (root, dirs, files) in walkdir(search_dir)
                for f in files
                    if f == "_jll_artifact_meta.json"
                        meta_path = joinpath(root, f)
                        try
                            meta_content = read(meta_path, String)
                            # Parse JSON manually (avoid dependency)
                            # Format: {"pkg_name":"...", "git_tree_sha1":"...", ...}
                            meta = _parse_simple_json(meta_content)

                            git_tree_sha1 = get(meta, "git_tree_sha1", "")
                            if !isempty(git_tree_sha1)
                                # The artifact directory is the parent of the metadata file
                                artifact_path = dirname(meta_path)
                                artifact_overrides[git_tree_sha1] = artifact_path
                                @debug "Found artifact: $git_tree_sha1 => $artifact_path"
                            end
                        catch e
                            @warn "Failed to parse artifact metadata at $meta_path: $e"
                        end
                    end
                end
            end
        end
    end

    # Also check if there are artifact repos in runfiles directly
    # These would be at paths like: runfiles_dir/<repo>__artifact__<pkg>__<name>__<platform>/
    if isdir(runfiles_dir)
        for entry in readdir(runfiles_dir)
            if occursin("__artifact__", entry)
                artifact_dir = joinpath(runfiles_dir, entry)
                if isdir(artifact_dir)
                    meta_path = joinpath(artifact_dir, "_jll_artifact_meta.json")
                    if isfile(meta_path)
                        try
                            meta_content = read(meta_path, String)
                            meta = _parse_simple_json(meta_content)
                            git_tree_sha1 = get(meta, "git_tree_sha1", "")
                            if !isempty(git_tree_sha1)
                                artifact_overrides[git_tree_sha1] = artifact_dir
                                @debug "Found artifact in runfiles root: $git_tree_sha1 => $artifact_dir"
                            end
                        catch e
                            @warn "Failed to parse artifact metadata at $meta_path: $e"
                        end
                    end
                end
            end
        end
    end

    if isempty(artifact_overrides)
        @debug "No JLL artifacts found in runfiles"
        return nothing
    end

    @debug "Found $(length(artifact_overrides)) JLL artifact overrides"

    # Write Overrides.toml to depot
    # Julia looks for this in the first writable depot at artifacts/Overrides.toml
    depot_path = first(DEPOT_PATH)
    artifacts_dir = joinpath(depot_path, "artifacts")
    mkpath(artifacts_dir)

    overrides_path = joinpath(artifacts_dir, "Overrides.toml")

    # Build Overrides.toml content
    # Format: <sha1> = "<path>"
    overrides_content = IOBuffer()
    println(overrides_content, "# Generated by rules_julia for Bazel-managed JLL artifacts")
    println(
        overrides_content,
        "# Do not edit manually - this file is regenerated on each run",
    )
    println(overrides_content)

    for (sha1, path) in sort(collect(artifact_overrides))
        # Escape backslashes for Windows paths in TOML
        escaped_path = replace(path, "\\" => "\\\\")
        println(overrides_content, "\"$sha1\" = \"$escaped_path\"")
    end

    overrides_str = String(take!(overrides_content))

    # Write the file
    open(overrides_path, "w") do f
        write(f, overrides_str)
    end

    @debug "Wrote artifact overrides to $overrides_path"

    return overrides_path
end

"""
    _parse_simple_json(content::String) -> Dict{String, String}

Simple JSON parser for flat objects with string values.
Avoids dependency on JSON.jl.
"""
function _parse_simple_json(content::String)
    result = Dict{String,String}()

    # Remove whitespace and braces
    content = strip(content)
    if startswith(content, "{") && endswith(content, "}")
        content = content[2:(end-1)]
    end

    # Split by commas (being careful about quoted strings)
    # Simple approach: regex for "key":"value" pairs
    for m in eachmatch(r"\"([^\"]+)\"\s*:\s*\"([^\"]+)\"", content)
        key = m.captures[1]
        value = m.captures[2]
        result[key] = value
    end

    return result
end

"""
    setup_julia_environment(include_paths, runfiles_dir, manifest_toml_path, project_toml_path)

Create a Julia environment by splicing runfiles paths into an existing Manifest.toml.

This approach:
1. Uses explicit paths for Project.toml and Manifest.toml (passed from Bazel config)
2. Builds a name => runfiles_path mapping from all discovered packages
3. Parses the existing Manifest.toml which Pkg already generated with correct structure
4. Replaces `git-tree-sha1` entries with `path` entries for packages in runfiles
5. Copies Project.toml and writes modified Manifest.toml to a temp directory
6. Activates that environment

This ensures packages like Preferences.jl, JLLWrappers, etc. work correctly because
the Manifest retains all the structure Pkg expects (stdlibs, extensions, weakdeps).
"""
function setup_julia_environment(
    include_paths,
    runfiles_dir,
    manifest_toml_path::String,
    project_toml_path::String,
)
    # If no manifest_toml provided, nothing to do
    if isempty(manifest_toml_path) || !isfile(manifest_toml_path)
        @debug "No Manifest.toml path provided or file doesn't exist, skipping environment setup"
        return nothing
    end

    if isempty(project_toml_path) || !isfile(project_toml_path)
        @debug "No Project.toml path provided or file doesn't exist, skipping environment setup"
        return nothing
    end

    @debug "Setting up environment from manifest: $manifest_toml_path"
    @debug "Project.toml: $project_toml_path"

    # Build a name => runfiles_path mapping from all include paths
    packages = Dict{String,String}()

    for inc_path in include_paths
        project_toml_candidates = [
            joinpath(inc_path, "Project.toml"),           # inc_path = Repo.jl
            joinpath(dirname(inc_path), "Project.toml"),  # inc_path = Repo.jl/src
        ]

        for project_path in project_toml_candidates
            if !isfile(project_path)
                continue
            end
            try
                proj = TOML.parsefile(project_path)
                name = get(proj, "name", nothing)
                if name !== nothing
                    pkg_root = dirname(project_path)
                    packages[name] = pkg_root
                    @debug "Found package in runfiles: $name at $pkg_root"
                end
            catch e
                @debug "Failed to parse Project.toml at $project_path: $e"
            end
            break  # Found a valid Project.toml, don't check other candidates
        end
    end

    if isempty(packages)
        @debug "No packages found with Project.toml, skipping environment setup"
        return nothing
    end

    # Parse the existing Manifest.toml
    manifest = TOML.parsefile(manifest_toml_path)
    deps = get(manifest, "deps", nothing)
    if deps === nothing
        @debug "Manifest.toml has no deps section"
        return nothing
    end

    # Splice paths into manifest entries
    # For each package entry, if we have a runfiles path for it, replace git-tree-sha1 with path
    for (pkg_name, entries) in deps
        # entries is a Vector of Dicts (manifest format 2.0)
        if !(entries isa Vector)
            continue
        end
        for entry in entries
            if !(entry isa Dict)
                continue
            end

            # Check if this package is in our runfiles
            if haskey(packages, pkg_name)
                runfiles_path = packages[pkg_name]

                # Remove git-tree-sha1 if present (we're using path instead)
                if haskey(entry, "git-tree-sha1")
                    delete!(entry, "git-tree-sha1")
                end

                # Add or update path entry
                if haskey(entry, "path")
                    if entry["path"] == "." ||
                       entry["path"] == ".." ||
                       entry["path"] == "..." ||
                       !isabspath(entry["path"])
                        entry["path"] = runfiles_path
                    end
                else
                    entry["path"] = runfiles_path
                end

                @debug "Updated manifest entry for $pkg_name => $runfiles_path"
            end
            # Note: stdlibs and packages not in runfiles keep their original entries
        end
    end

    @debug "Processed $(length(packages)) package entries"

    # Create temp environment with modified Manifest
    temp_base = get(ENV, "TEST_TMPDIR", tempdir())
    env_dir = mktempdir(temp_base; prefix = "julia_env_")

    # Copy original Project.toml
    cp(project_toml_path, joinpath(env_dir, "Project.toml"))
    cp(joinpath(dirname(project_toml_path), "src"), joinpath(env_dir, "src"))

    # Copy LocalPreferences.toml if it exists (for MPI variant selection, etc.)
    # This ensures runtime platform augmentation selects the same artifact variant
    # that was downloaded at build time.
    local_prefs_path = joinpath(dirname(project_toml_path), "LocalPreferences.toml")
    if isfile(local_prefs_path)
        content = read(local_prefs_path, String)
        # Expand __RUNFILES_DIR__ placeholders before writing
        # Using the regular cp() Julia function mysteriously results in altering the
        # contents of the source LocalPreferences.toml (are these symlinks?). Writing to
        # dest_path avoids this.
        if occursin("__RUNFILES_DIR__", content)
            content = replace(content, "__RUNFILES_DIR__" => runfiles_dir)
            @debug "Expanded __RUNFILES_DIR__ in LocalPreferences.toml: $runfiles_dir"
        end
        dest_path = joinpath(env_dir, "LocalPreferences.toml")
        write(dest_path, content)
        @debug "Wrote LocalPreferences.toml to env_dir: $dest_path"
    end

    # Write modified Manifest.toml
    open(joinpath(env_dir, "Manifest.toml"), "w") do f
        TOML.print(f, manifest)
    end

    @debug "Created environment at $env_dir"

    # Activate this environment
    pushfirst!(LOAD_PATH, env_dir)

    @debug "Activated spliced environment, LOAD_PATH now has $(length(LOAD_PATH)) entries"

    return env_dir
end
