# Shared code for the rules_julia entrypoint and build-time drivers.
#
# All of them work on the same model: a runfiles-shaped tree (the binary's
# runfiles directory at run time, a tree materialized from a manifest at build
# time) plus a config file listing include paths and precompile depots
# relative to that tree.

import TOML

const DEBUG = haskey(ENV, "RULES_JULIA_DEBUG")

function debug(msg)
    if DEBUG
        println(stderr, "[rules_julia] ", msg)
    end
end

"""
    parse_flags(args; scalars, lists) -> Dict{String,Any}

Parse `--flag value` pairs. Flags in `lists` may repeat and collect into a
vector; flags in `scalars` take the last value.
"""
function parse_flags(args::Vector{String}; scalars = String[], lists = String[])
    values = Dict{String,Any}(name => String[] for name in lists)
    i = 1
    while i <= length(args)
        flag = args[i]
        i < length(args) || error("Missing value for $flag")
        if flag in scalars
            values[flag] = args[i+1]
        elseif flag in lists
            push!(values[flag], args[i+1])
        else
            error("Unknown argument: $flag")
        end
        i += 2
    end
    return values
end

function require_flag(values::Dict{String,Any}, flag::String)::String
    haskey(values, flag) || error("$flag is required")
    return values[flag]
end

"""
    read_config(path) -> (includes, depots, runfiles)

Read a rules_julia config file. All entries are paths relative to the
runfiles root.
"""
function read_config(path::String)
    isfile(path) || return (String[], String[], String[])
    config = TOML.parsefile(path)
    entries(key) = collect(String, get(config, key, String[]))
    return (entries("includes"), entries("depots"), entries("runfiles"))
end

"""
    install_tree(manifest, root; keep) -> Dict{String,String}

Materialize a runfiles-shaped tree from a manifest of `rlocationpath realpath`
lines (Bazel's runfiles manifest or one generated by the rules). Only entries
for which `keep(rlocationpath)` is true are installed. Symlinks are used where
available; Windows falls back to copies.
"""
function install_tree(manifest::String, root::String; keep = _ -> true)
    use_symlinks = !Sys.iswindows()
    installed = Dict{String,String}()
    for line in eachline(manifest)
        line = strip(line)
        isempty(line) && continue
        parts = split(line, " ", limit = 2)
        length(parts) == 2 || error("Malformed manifest line: $line")
        rlocation, path = String(parts[1]), String(parts[2])
        keep(rlocation) || continue
        src = abspath(path)
        ispath(src) || continue
        dest = joinpath(root, rlocation)
        mkpath(dirname(dest))
        if use_symlinks
            try
                symlink(src, dest)
            catch
                cp(src, dest; force = true)
            end
        else
            cp(src, dest; force = true)
        end
        installed[rlocation] = src
    end
    return installed
end

"""
    configure_depots!(root, depots)

Make build-time precompile caches visible. `root` (the runfiles root) is added
so that `@depot`-relative source paths recorded at build time resolve, followed
by every depot. They are inserted after the first `DEPOT_PATH` entry, which is
the writable depot when one is configured.
"""
function configure_depots!(root::String, depots::Vector{String})
    dirs = [root; [normpath(joinpath(root, depot)) for depot in depots]]
    position = isempty(DEPOT_PATH) ? 1 : 2
    for (i, dir) in enumerate(dirs)
        insert!(DEPOT_PATH, position + i - 1, dir)
    end
    return DEPOT_PATH
end

"""
    append_bundled_depots!(depots)

Append Julia's bundled depots (stdlib compile caches, artifacts) to `depots`.
`Base.append_bundled_depot_path!` only exists on Julia 1.11+.
"""
function append_bundled_depots!(depots::Vector{String})
    if isdefined(Base, :append_bundled_depot_path!)
        Base.append_bundled_depot_path!(depots)
    else
        push!(depots, abspath(Sys.BINDIR, "..", "local", "share", "julia"))
        push!(depots, abspath(Sys.BINDIR, "..", "share", "julia"))
    end
    return depots
end

"""
    add_includes!(root, includes) -> Vector{String}

Append the include paths (resolved against `root`) to `LOAD_PATH`.
"""
function add_includes!(root::String, includes::Vector{String})
    paths = [normpath(joinpath(root, inc)) for inc in includes]
    for path in paths
        path in LOAD_PATH || push!(LOAD_PATH, path)
    end
    return paths
end
