load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load(
    ":settings.bzl",
    "cxxstring_abi",
    "formatter_config",
    "libc",
    "libgfortran_version",
    "linker",
    "version",
)

package(default_visibility = ["//visibility:public"])

bzl_library(
    name = "settings_bzl",
    srcs = glob(["*.bzl"]),
    visibility = ["//julia/private:__pkg__"],
    deps = [
        "@bazel_skylib//lib:selects",
        "@bazel_skylib//rules:common_settings",
    ],
)

formatter_config()

linker()

version()

libc()

libgfortran_version()

cxxstring_abi()
