"""Rules for testing Julia Manifest synchronization"""

load("//julia/private:julia_common.bzl", "julia_common")
load("//julia/private:providers.bzl", "JuliaInfo")

def _julia_pkg_test_impl(ctx):
    manifest_toml = ctx.file.julia_manifest
    manifest_bazel_json = ctx.file.bazel_manifest

    # Curate values for the common implementation
    # Use the test runner's main source file as srcs
    curated_srcs = [ctx.file._test_runner_main]

    # Include the test runner binary as a dependency
    curated_deps = [ctx.attr._test_runner]

    # Include manifest files as data
    curated_data_files = [manifest_toml, manifest_bazel_json]
    curated_data_targets = []

    # Set environment variables for manifest file locations
    curated_env = {
        "RULES_JULIA_PKG_TEST_MANIFEST_BAZEL_JSON": julia_common.rlocationpath(manifest_bazel_json, ctx.workspace_name),
        "RULES_JULIA_PKG_TEST_MANIFEST_TOML": julia_common.rlocationpath(manifest_toml, ctx.workspace_name),
    }

    # Call the common implementation with curated values
    return julia_common.create_julia_binary_impl(
        ctx = ctx,
        srcs = curated_srcs,
        deps = curated_deps,
        data_files = curated_data_files,
        data_targets = curated_data_targets,
        env = curated_env,
        main = ctx.file._test_runner_main,
    )

julia_pkg_test = rule(
    doc = """\
A test rule that verifies Manifest.bazel.json is in sync with Manifest.toml.

This test ensures that the lockfile generated by pkg_compiler contains the correct
package versions, UUIDs, and dependencies that match the Manifest.toml file.

The test will fail if:
- A package is missing from the lockfile
- Versions don't match between the two files
- UUIDs don't match
- The git-tree-sha1 is not in the package URL
- SHA256 hashes are missing

Example:

```python
julia_pkg_test(
    name = "pkg_sync_test",
    manifest_toml = "Manifest.toml",
    manifest_bazel_json = "Manifest.bazel.json",
)
```

Then run:

```sh
bazel test //:pkg_sync_test
```

This will verify that both manifest files are synchronized. If they're out of sync,
the test will fail with detailed error messages indicating what needs to be fixed.
""",
    implementation = _julia_pkg_test_impl,
    attrs = {
        "bazel_manifest": attr.label(
            doc = "The Manifest.bazel.json lockfile to verify.",
            allow_single_file = True,
            mandatory = True,
        ),
        "julia_manifest": attr.label(
            doc = "The Manifest.toml file to compare against.",
            allow_single_file = ["Manifest.toml", ".toml"],
            mandatory = True,
        ),
        "_bash_runfiles": attr.label(
            default = Label("@bazel_tools//tools/bash/runfiles"),
        ),
        "_entrypoint": attr.label(
            default = Label("//julia/private:entrypoint.jl"),
            allow_single_file = True,
        ),
        "_test_runner": attr.label(
            doc = "The pkg test runner binary.",
            cfg = "target",
            providers = [JuliaInfo],
            default = Label("//julia/pkg/private:pkg_tester"),
        ),
        "_test_runner_main": attr.label(
            doc = "The test runner's main source file.",
            allow_single_file = [".jl"],
            default = Label("//julia/pkg/private:pkg_tester.jl"),
        ),
        "_wrapper_template": attr.label(
            default = Label("//julia/private:binary_wrapper.tpl"),
            allow_single_file = True,
        ),
    },
    test = True,
    toolchains = [julia_common.TOOLCHAIN_TYPE],
)
