"""A repository rule fetching a single Julia artifact.

Julia locates artifacts by searching every depot on `DEPOT_PATH` for
`artifacts/<git-tree-sha1>/`. The repository extracts the artifact tarball
into exactly that layout so the repository root can serve as a depot at
build and run time.
"""

_BUILD_FILE = """\
\"\"\"Autogenerated by rules_julia: the `{artifact}` artifact of `{package}`.\"\"\"

load("@rules_julia//julia/pkg/private:julia_artifact.bzl", "julia_artifact")

julia_artifact(
    name = "artifact",
    srcs = glob(
        ["artifacts/**"],
        allow_empty = True,
    ),
    artifact_name = "{artifact}",
    tree_hash = "{tree_hash}",
    visibility = ["//visibility:public"],
)
"""

def _julia_artifact_repository_impl(repository_ctx):
    attrs = repository_ctx.attr
    repository_ctx.report_progress("Fetching Julia artifact `{}` for `{}`".format(attrs.artifact_name, attrs.package))

    # BinaryBuilder tarballs have no top level directory and are always
    # gzipped tarballs, even when served from URLs without an extension.
    repository_ctx.download_and_extract(
        url = attrs.urls,
        sha256 = attrs.sha256,
        output = "artifacts/{}".format(attrs.tree_hash),
        type = "tar.gz",
    )

    repository_ctx.file("WORKSPACE.bazel", """workspace(name = "{}")""".format(
        repository_ctx.name,
    ))
    repository_ctx.file("BUILD.bazel", _BUILD_FILE.format(
        artifact = attrs.artifact_name,
        package = attrs.package,
        tree_hash = attrs.tree_hash,
    ))

    return repository_ctx.repo_metadata(reproducible = True) if hasattr(repository_ctx, "repo_metadata") else None

julia_artifact_repository = repository_rule(
    doc = "Fetch a Julia artifact into the `artifacts/<git-tree-sha1>` layout of a depot.",
    implementation = _julia_artifact_repository_impl,
    attrs = {
        "artifact_name": attr.string(
            doc = "The name of the artifact in `Artifacts.toml`.",
            mandatory = True,
        ),
        "package": attr.string(
            doc = "The package the artifact belongs to; used in messages.",
            mandatory = True,
        ),
        "sha256": attr.string(
            doc = "The expected SHA-256 of the tarball.",
            mandatory = True,
        ),
        "tree_hash": attr.string(
            doc = "The git tree hash of the extracted artifact.",
            mandatory = True,
        ),
        "urls": attr.string_list(
            doc = "URLs to fetch the tarball from.",
            mandatory = True,
        ),
    },
)
