"""Bazel tools for interfacing with Julia packages"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("//julia/settings:settings.bzl", "julia_minor_version", "julia_minor_versions")
load(":artifact_repository.bzl", "julia_artifact_repository")
load(":artifacts_toml.bzl", "parse_artifacts_toml")
load(":manifest_toml.bzl", "parse_manifest_toml")
load(":platforms.bzl", "choose_variants", "config_setting_text")

_VERSION_SETTING = "@rules_julia//julia/settings:version_{}"

_HUB_BUILD_HEADER = """\
\"\"\"Autogenerated by rules_julia.\"\"\"

load("@rules_julia//julia:julia_library.bzl", "julia_library")
"""

_PKG_BUILD_FILE = """\
\"\"\"Autogenerated by rules_julia.\"\"\"

load("@rules_julia//julia:julia_library.bzl", "julia_library")

DEPENDENCIES = {dependencies}

# Prebuilt artifacts, selected for the target platform.
ARTIFACTS = {artifact_deps}

# The Julia minor version the manifest was resolved for, if any.
COMPATIBLE_WITH = {compatible_with}

julia_library(
    name = "{name}",
    srcs = glob(
        include = [
            "src/**/*.jl",
            "ext/**/*.jl",
        ],
        allow_empty = True,
    ),
    data = glob(
        include = [
            "*.toml",
            "src/**",
            "ext/**",
        ],
        exclude = [
            # A committed manifest would override dependency resolution.
            "Manifest.toml",
            "JuliaManifest.toml",
            "src/**/*.jl",
            "ext/**/*.jl",
        ],
        allow_empty = True,
    ),
    deps = [
        "@{prefix}__" + dep
        for dep in DEPENDENCIES
    ] + ARTIFACTS,
    tags = [
        "julia_pkg_version={version}",
        "julia_pkg_uuid={uuid}",
    ],
    target_compatible_with = COMPATIBLE_WITH,
    visibility = ["//visibility:public"],
)

alias(
    name = "{repo_name}",
    actual = "{name}",
    visibility = ["//visibility:public"],
)
"""

def _quote_list(items, indent):
    pad = " " * indent
    if not items:
        return "[]"
    return "[\n" + "".join(["{}    \"{}\",\n".format(pad, item) for item in items]) + pad + "]"

def _hub_build_file(hub_name, graphs, config_settings):
    """Render the hub BUILD file.

    Args:
        hub_name (str): The hub repository name.
        graphs (list[dict]): One entry per manifest with keys `prefix` (repository
            name prefix of its packages), `minor` (Julia minor version or `None`)
            and `packages` (list of package names).
        config_settings (list[str]): `config_setting` definitions for artifacts.

    Returns:
        str: The BUILD file content.
    """
    lines = [_HUB_BUILD_HEADER]

    all_packages = {}
    for graph in graphs:
        for package in graph["packages"]:
            all_packages.setdefault(package, []).append(graph)

    if len(graphs) == 1:
        graph = graphs[0]
        lines.append("julia_library(")
        lines.append("    name = \"{}\",".format(hub_name))
        lines.append("    srcs = [],")
        lines.append("    deps = {},".format(_quote_list(["@{}__{}".format(graph["prefix"], pkg) for pkg in graph["packages"]], 4)))
        if graph["minor"] != None:
            lines.append("    target_compatible_with = select({")
            lines.append("        \"{}\": [],".format(_VERSION_SETTING.format(graph["minor"])))
            lines.append("        \"//conditions:default\": [\"@platforms//:incompatible\"],")
            lines.append("    }),")
        lines.append("    visibility = [\"//visibility:public\"],")
        lines.append(")")
        lines.append("")
        for package in sorted(all_packages.keys()):
            lines.append("alias(")
            lines.append("    name = \"{}\",".format(package))
            lines.append("    actual = \"@{}__{}\",".format(graph["prefix"], package))
            lines.append("    visibility = [\"//visibility:public\"],")
            lines.append(")")
            lines.append("")
    else:
        # Several manifests: select the graph by Julia minor version. A
        # package absent from the selected graph resolves to one that has it,
        # which is incompatible with the selected version, so dependents are
        # skipped rather than failing analysis.
        lines.append("julia_library(")
        lines.append("    name = \"{}\",".format(hub_name))
        lines.append("    srcs = [],")
        lines.append("    deps = select({")
        for graph in graphs:
            lines.append("        \"{}\": {},".format(
                _VERSION_SETTING.format(graph["minor"]),
                _quote_list(["@{}__{}".format(graph["prefix"], pkg) for pkg in graph["packages"]], 8),
            ))
        lines.append("        \"//conditions:default\": [],")
        lines.append("    }),")
        lines.append("    target_compatible_with = select({")
        for graph in graphs:
            lines.append("        \"{}\": [],".format(_VERSION_SETTING.format(graph["minor"])))
        lines.append("        \"//conditions:default\": [\"@platforms//:incompatible\"],")
        lines.append("    }),")
        lines.append("    visibility = [\"//visibility:public\"],")
        lines.append(")")
        lines.append("")
        for package in sorted(all_packages.keys()):
            providers = all_packages[package]
            lines.append("alias(")
            lines.append("    name = \"{}\",".format(package))
            lines.append("    actual = select({")
            for graph in providers:
                lines.append("        \"{}\": \"@{}__{}\",".format(
                    _VERSION_SETTING.format(graph["minor"]),
                    graph["prefix"],
                    package,
                ))
            lines.append("        \"//conditions:default\": \"@{}__{}\",".format(providers[0]["prefix"], package))
            lines.append("    }),")
            lines.append("    visibility = [\"//visibility:public\"],")
            lines.append(")")
            lines.append("")

    minors = [graph["minor"] for graph in graphs if graph["minor"] != None]
    if minors:
        lines.append("# Julia versions the manifests are resolved for: {}".format(", ".join(minors)))
        lines.append("")

    if config_settings:
        lines.append("# Platforms artifacts of these packages are available for.")
        lines.append("\n\n".join(config_settings))
        lines.append("")

    return "\n".join(lines)

def _pkg_hub_impl(repository_ctx):
    repository_ctx.file("WORKSPACE.bazel", """workspace(name = "{}")""".format(
        repository_ctx.name,
    ))
    repository_ctx.file("BUILD.bazel", _hub_build_file(
        repository_ctx.attr.hub_name,
        json.decode(repository_ctx.attr.graphs),
        repository_ctx.attr.config_settings,
    ))

pkg_hub = repository_rule(
    implementation = _pkg_hub_impl,
    attrs = {
        "config_settings": attr.string_list(
            doc = "`config_setting` definitions for the platforms artifacts are available for.",
            default = [],
        ),
        "graphs": attr.string(
            doc = "JSON list of package graphs: `prefix`, `minor` and `packages` per manifest.",
            mandatory = True,
        ),
        "hub_name": attr.string(
            mandatory = True,
        ),
    },
)

def _read_lockfile_json(module_ctx, lockfile_path):
    """Read and parse the Manifest.bazel.json lockfile.

    Returns a dictionary mapping package names to package data including SHA256 hashes.
    """
    lockfile = module_ctx.path(lockfile_path)
    module_ctx.watch(lockfile)
    content = module_ctx.read(lockfile)

    # Parse JSON content
    packages = json.decode(content)

    return packages

def _package_url(pkg_server, uuid, tree_hash):
    return "{}/package/{}/{}".format(pkg_server.rstrip("/"), uuid, tree_hash)

def _fact_data(fact):
    """Extract `(integrity, artifacts)` from a persisted fact.

    Returns `None` when the fact is missing or was written with an older
    schema, in which case the package is fetched again.
    """
    if type(fact) != "dict":
        return None
    integrity = fact.get("integrity")
    artifacts = fact.get("artifacts")
    if not integrity or type(artifacts) != "dict":
        return None
    return struct(integrity = integrity, artifacts = artifacts)

def _read_artifacts(module_ctx, package_dir, label):
    """Read the `Artifacts.toml` of an extracted package, if any."""
    for candidate in ["Artifacts.toml", "JuliaArtifacts.toml"]:
        path = package_dir.get_child(candidate)
        if path.exists:
            return parse_artifacts_toml(module_ctx.read(path), label = "{}:{}".format(label, candidate))
    return {}

def _packages_from_manifest(module_ctx, attrs, manifest_label, facts):
    """Build package data from a `Manifest.toml`, using facts for integrity values.

    Every non-stdlib package in the manifest is mapped to a package server URL
    derived from its UUID and git tree hash. Integrity values are looked up in
    `facts`. Any package without a known integrity value is downloaded once so
    the value can be computed and persisted for future evaluations.

    Args:
        module_ctx (module_ctx): The current module context.
        attrs (struct): The attributes from the `install` tag class.
        manifest_label (Label): The manifest to read.
        facts (dict): Facts persisted by previous evaluations of the extension (a `Facts` object or a dict).

    Returns:
        struct: With fields `packages` (dict matching the layout of
            `Manifest.bazel.json`), `facts` (dict mapping every URL used to the
            data to persist for it) and `minor` (str, the Julia minor version
            the manifest was resolved with).
    """
    manifest_path = module_ctx.path(manifest_label)
    module_ctx.watch(manifest_path)
    manifest = parse_manifest_toml(
        module_ctx.read(manifest_path),
        label = str(manifest_label),
    )

    if not manifest.julia_version:
        fail("{} does not record a `julia_version`; it was not written by a supported Pkg".format(manifest_label))
    minor = julia_minor_version(str(manifest.julia_version))
    if minor not in julia_minor_versions():
        fail("{} was resolved with Julia {}, for which rules_julia knows no toolchain. Known minor versions: {}".format(
            manifest_label,
            manifest.julia_version,
            ", ".join(julia_minor_versions()),
        ))

    packages = {}
    used_facts = {}
    pending = {}
    for name, entry in manifest.packages.items():
        # Standard library packages ship with Julia and have no tree hash.
        if not entry["tree_hash"]:
            continue

        url = _package_url(attrs.pkg_server, entry["uuid"], entry["tree_hash"])
        packages[name] = {
            "deps": entry["deps"],
            "integrity": "",
            "urls": [url],
            "uuid": entry["uuid"],
            "version": entry["version"] or "",
        }

        known = _fact_data(facts.get(url))
        if known:
            packages[name]["integrity"] = known.integrity
            packages[name]["artifacts"] = known.artifacts
            used_facts[url] = {"artifacts": known.artifacts, "integrity": known.integrity}
        else:
            pending[name] = url

    if pending:
        module_ctx.report_progress("Computing integrity for {} Julia package(s) from {}".format(
            len(pending),
            manifest_label,
        ))

        # Start all downloads before waiting on any of them.
        tokens = {}
        archives = {}
        for name, url in pending.items():
            archives[name] = "{}/{}-{}.tar.gz".format(attrs.name, name, packages[name]["uuid"])
            tokens[name] = module_ctx.download(
                url = [url],
                output = archives[name],
                block = False,
            )

        for name, token in tokens.items():
            result = token.wait()
            url = pending[name]
            if not result.success:
                fail("Failed to download Julia package `{}` from `{}` while computing its integrity for `{}`".format(
                    name,
                    url,
                    manifest_label,
                ))

            # The package is unpacked once to read its `Artifacts.toml`. The
            # result is persisted in facts so this never happens again for
            # the same URL. The scratch files live in the extension's working
            # directory, which Bazel discards after evaluation.
            package_dir = archives[name][:-len(".tar.gz")]
            module_ctx.extract(archive = archives[name], output = package_dir)
            artifacts = _read_artifacts(module_ctx, module_ctx.path(package_dir), "{} ({})".format(manifest_label, name))

            packages[name]["integrity"] = result.integrity
            packages[name]["artifacts"] = artifacts
            used_facts[url] = {"artifacts": artifacts, "integrity": result.integrity}

    return struct(packages = packages, facts = used_facts, minor = minor)

def _sanitize(text):
    """Restrict `text` to characters valid in repository and target names."""
    result = ""
    for i in range(len(text)):
        char = text[i]
        if char.isalnum() or char in "_-.":
            result += char
        else:
            result += "_"
    return result

def _artifact_repositories(*, hub, prefix, package, artifacts, pkg_server, config_settings):
    """Define repositories for a package's artifacts and render its `ARTIFACTS` deps.

    Args:
        hub (str): The hub repository name, which defines the `config_setting`s.
        prefix (str): The repository name prefix of the package's graph.
        package (str): The package name.
        artifacts (dict): Artifact variants keyed by artifact name.
        pkg_server (str): The package server, used as a mirror for artifacts.
        config_settings (dict): Accumulates `config_setting` texts keyed by name.

    Returns:
        str: Starlark text for the package's `ARTIFACTS` list.
    """
    unconditional = []
    selects = []
    for artifact_name in sorted(artifacts.keys()):
        variants = artifacts[artifact_name]
        choice = choose_variants(variants)

        # Julia downloads lazy artifacts on first use, so a package may well
        # not have one for every platform it supports. Such an artifact is
        # fetched like any other where a variant exists and omitted
        # elsewhere, deferring the failure to the point of use as Julia does.
        lazy = any([variant["lazy"] for variant in variants])
        branches = {}
        available = []
        for key_name, selection in choice.selected.items():
            variant = selection.variant
            if not variant["sha256"]:
                fail("Artifact `{}` of package `{}` has no sha256 for platform {}".format(
                    artifact_name,
                    package,
                    variant["tags"],
                ))
            suffix = key_name[len("platform__"):] if key_name else "any"
            repo_name = "{}__{}__{}__{}".format(prefix, package, _sanitize(artifact_name), suffix)
            julia_artifact_repository(
                name = repo_name,
                artifact_name = artifact_name,
                package = package,
                sha256 = variant["sha256"],
                tree_hash = variant["tree_hash"],
                urls = variant["urls"] + ["{}/artifact/{}".format(pkg_server.rstrip("/"), variant["tree_hash"])],
            )
            label = "@{}//:artifact".format(repo_name)
            if key_name:
                config_settings.setdefault(key_name, config_setting_text(selection.key))
                branches["@{}//:{}".format(hub, key_name)] = label
                available.append(suffix)
            else:
                unconditional.append(label)

        if branches:
            lines = ["select({"]
            for condition in sorted(branches.keys()):
                lines.append("        \"{}\": [\"{}\"],".format(condition, branches[condition]))
            if lazy:
                lines.append("        \"//conditions:default\": [],")
                lines.append("    })")
            else:
                message = (
                    "No `{}` artifact of `{}` is available for the target platform. " +
                    "Available platforms: {}. Check the `@rules_julia//julia/settings` " +
                    "`libc`, `libgfortran_version` and `cxxstring_abi` flags if the " +
                    "platform looks right."
                ).format(
                    artifact_name,
                    package,
                    ", ".join(sorted(available)),
                )
                lines.append("    }, no_match_error = \"" + message + "\")")
            selects.append("\n    ".join(lines))

    text = "[" + "".join(["\n    \"{}\",".format(label) for label in unconditional]) + ("\n]" if unconditional else "]")
    for select_text in selects:
        text += " + " + select_text
    return text

def _define_graph(*, attrs, prefix, minor, packages, annotations, config_settings):
    """Define the repositories of one package graph.

    Args:
        attrs (struct): The attributes from the `install` tag class.
        prefix (str): Repository name prefix for the graph's packages.
        minor (str): The Julia minor version the graph is for, or `None` when unknown.
        packages (dict): Package data in the layout of `Manifest.bazel.json`.
        annotations (dict): Package annotations.
        config_settings (dict): Accumulates artifact `config_setting` texts by name.
    """
    all_package_names = list(packages.keys())

    if minor == None:
        compatible_with = "[]"
    else:
        compatible_with = (
            "select({\n" +
            "    \"" + _VERSION_SETTING.format(minor) + "\": [],\n" +
            "    \"//conditions:default\": [\"@platforms//:incompatible\"],\n" +
            "})"
        )

    for package_name, package_data in packages.items():
        urls = package_data.get("urls", [])
        version = package_data.get("version", "")
        uuid = package_data.get("uuid", "")
        all_deps = package_data.get("deps", [])

        if not urls:
            fail("Package {} missing URLs in lockfile".format(package_name))
        if not uuid:
            fail("Package {} missing UUID in lockfile".format(package_name))

        # Filter dependencies to only include packages in this graph
        deps = [dep for dep in all_deps if dep in all_package_names]

        repo_name = "{}__{}".format(prefix, package_name)
        package_annotations = annotations.get(package_name)

        artifact_deps = _artifact_repositories(
            hub = attrs.name,
            prefix = prefix,
            package = package_name,
            artifacts = package_data.get("artifacts", {}),
            pkg_server = attrs.pkg_server,
            config_settings = config_settings,
        )

        http_archive_args = {
            "build_file_content": _PKG_BUILD_FILE.format(
                name = package_name,
                dependencies = deps,
                artifact_deps = artifact_deps,
                compatible_with = compatible_with,
                prefix = prefix,
                repo_name = repo_name,
                version = version,
                uuid = uuid,
            ),
            "integrity": package_data.get("integrity", ""),
            "name": repo_name,
            "sha256": package_data.get("sha256", ""),
            "type": "tar.gz",
            "urls": urls,
        }

        if package_annotations:
            if "patches" in package_annotations:
                http_archive_args["patches"] = package_annotations["patches"]
            if "patch_args" in package_annotations:
                http_archive_args["patch_args"] = package_annotations["patch_args"]
            if "patch_tool" in package_annotations:
                http_archive_args["patch_tool"] = package_annotations["patch_tool"]

        http_archive(**http_archive_args)

def install(*, module_ctx, attrs, annotations = {}, facts = {}):
    """Instantiate the pkg module for the given `install` tag_class attributes.

    Args:
        module_ctx (module_ctx): The current module context.
        attrs (struct): The attributes from the `install` tag class.
        annotations (dict): Optional dictionary mapping package names to annotation data.
        facts (dict): Facts persisted by previous evaluations of the extension (a `Facts` object or a dict).

    Returns:
        struct: With the fields:
            - `hub` (str): The name of the hub repository for the current tag_class.
            - `facts` (dict): Facts that should be persisted for future evaluations.
            - `from_manifest` (bool): Whether packages were derived from `Manifest.toml`.
    """
    manifests = list(attrs.manifests)
    if attrs.manifest:
        manifests.append(attrs.manifest)

    if attrs.lockfile and manifests:
        fail("`pkg.install(name = \"{}\")` sets both `lockfile` and `manifests`. Only one may be set.".format(attrs.name))
    if not attrs.lockfile and not manifests:
        fail("`pkg.install(name = \"{}\")` requires either `manifests` or `lockfile` to be set.".format(attrs.name))

    used_facts = {}
    from_manifest = False

    # One graph per manifest, keyed by the Julia minor version it is for.
    graphs = []
    if attrs.lockfile:
        graphs.append(struct(minor = None, packages = _read_lockfile_json(module_ctx, attrs.lockfile)))
    else:
        from_manifest = True
        seen = {}
        for manifest in manifests:
            graph = _packages_from_manifest(module_ctx, attrs, manifest, facts)
            if graph.minor in seen:
                fail("`pkg.install(name = \"{}\")`: {} and {} are both resolved for Julia {}".format(
                    attrs.name,
                    seen[graph.minor],
                    manifest,
                    graph.minor,
                ))
            seen[graph.minor] = manifest
            used_facts.update(graph.facts)
            graphs.append(struct(minor = graph.minor, packages = graph.packages))
        graphs = sorted(graphs, key = lambda graph: [int(p) for p in graph.minor.split(".")])

    config_settings = {}
    rendered = []
    for graph in graphs:
        if len(graphs) == 1:
            prefix = attrs.name
        else:
            prefix = "{}__v{}".format(attrs.name, graph.minor.replace(".", "_"))
        _define_graph(
            attrs = attrs,
            prefix = prefix,
            minor = graph.minor,
            packages = graph.packages,
            annotations = annotations,
            config_settings = config_settings,
        )
        rendered.append({
            "minor": graph.minor,
            "packages": sorted(graph.packages.keys()),
            "prefix": prefix,
        })

    pkg_hub(
        name = attrs.name,
        hub_name = attrs.name,
        graphs = json.encode(rendered),
        config_settings = [config_settings[key] for key in sorted(config_settings.keys())],
    )

    return struct(
        facts = used_facts,
        from_manifest = from_manifest,
        hub = attrs.name,
    )
