"""
Julia Package Lockfile Test (per manifest)

Verifies one `Manifest.toml` under the Julia version that resolved it:

- `Manifest.toml` must have been resolved from the current `Project.toml`.
- When a `Manifest.bazel.json` is tracked, it must be in sync with `Manifest.toml`.

Paths arrive as absolute paths in the environment; `pkg_tester.jl` resolves
runfiles and launches this script once per manifest with the matching Julia.
Since external JSON packages are unavailable, the JSON checks are textual.
"""

using Pkg

function parse_manifest_toml(manifest_path::String)
    """Parse Manifest.toml and extract package information."""
    manifest = Pkg.Types.read_manifest(manifest_path)

    packages = Dict{String,Any}()

    for (uuid, pkg_entry) in manifest
        # Skip Julia stdlib packages (they don't have a tree hash)
        if !isdefined(pkg_entry, :tree_hash) || isnothing(pkg_entry.tree_hash)
            continue
        end

        name = pkg_entry.name
        tree_hash = string(pkg_entry.tree_hash)
        version = string(pkg_entry.version)
        uuid_str = string(uuid)

        packages[name] =
            Dict("uuid" => uuid_str, "version" => version, "git-tree-sha1" => tree_hash)
    end

    return packages
end

minor(v::VersionNumber) = (v.major, v.minor)

function check_manifest_current(
    project_toml::String,
    manifest_toml::String,
    expected_version::VersionNumber,
)
    """Verify Manifest.toml was resolved from the current Project.toml.

    Pkg records a hash of the project's dependencies and compat entries in the
    manifest's `project_hash` field whenever it resolves. Comparing it with the
    hash of the current project detects edits to Project.toml that were not
    followed by a run of the compiler.

    The hash algorithm is defined by Pkg and differs between Julia minor
    versions, so this runs under the Julia the manifest is declared for.
    """
    errors = String[]

    # Pkg expects both files side by side with their canonical names.
    env_dir = mktempdir(prefix = "rjlpt_", cleanup = true)
    cp(project_toml, joinpath(env_dir, "Project.toml"))
    cp(manifest_toml, joinpath(env_dir, "Manifest.toml"))

    env = Pkg.Types.EnvCache(joinpath(env_dir, "Project.toml"))
    resolved = env.manifest.julia_version

    if resolved === nothing
        push!(errors, "Manifest.toml does not record the Julia version that resolved it.")
        return errors
    end

    if minor(resolved) != minor(expected_version)
        push!(
            errors,
            "Manifest.toml was resolved with Julia $(resolved) but is declared for Julia " *
            "$(expected_version) in the `manifests` attribute. Re-run the compiler to " *
            "resolve it with Julia $(expected_version), or fix the declaration.",
        )
        return errors
    end

    if minor(VERSION) != minor(resolved)
        push!(
            errors,
            "This check runs under Julia $(VERSION) but the manifest was resolved with " *
            "Julia $(resolved); no matching toolchain was selected.",
        )
        return errors
    end

    # `is_manifest_current` returns `nothing` when the manifest records no
    # `project_hash`, `false` when Project.toml changed since the last
    # resolve, and `true` otherwise.
    current = Pkg.Operations.is_manifest_current(env)

    if current === nothing
        push!(
            errors,
            "Manifest.toml does not record a `project_hash`. It was not generated by a supported version of Pkg.",
        )
    elseif current === false
        recorded = get(env.manifest.other, "project_hash", "<missing>")
        push!(
            errors,
            "Manifest.toml is out of date: Project.toml changed since the manifest (project_hash `$recorded`) was resolved.",
        )
    end

    return errors
end

function check_lockfile_basic(lockfile_path::String, toml_packages::Dict)
    """Do basic validation checks on the lockfile."""
    errors = String[]
    content = read(lockfile_path, String)

    # Check that the file is valid JSON (basic check)
    if !startswith(strip(content), "{") || !endswith(strip(content), "}")
        push!(errors, "Manifest.bazel.json is not a valid JSON object")
        return errors
    end

    # Check that each package from TOML is mentioned in the JSON
    for (name, toml_data) in toml_packages
        # Check package name exists
        if !contains(content, "\"$name\"")
            push!(
                errors,
                "Package '$name' from Manifest.toml not found in Manifest.bazel.json",
            )
            continue
        end

        # Check version is mentioned
        version = toml_data["version"]
        if !contains(content, "\"version\": \"$version\"")
            push!(
                errors,
                "Package '$name': version '$version' from Manifest.toml not found in Manifest.bazel.json",
            )
        end

        # Check UUID is mentioned
        uuid = toml_data["uuid"]
        if !contains(content, "\"uuid\": \"$uuid\"")
            push!(
                errors,
                "Package '$name': UUID '$uuid' from Manifest.toml not found in Manifest.bazel.json",
            )
        end

        # Check git-tree-sha1 is in a URL
        tree_hash = toml_data["git-tree-sha1"]
        if !contains(content, tree_hash)
            push!(
                errors,
                "Package '$name': git-tree-sha1 '$tree_hash' from Manifest.toml not found in any URL in Manifest.bazel.json",
            )
        end

        # Check that the integrity field exists for this package
        # Look for the pattern after the package name
        pkg_section_start = findfirst("\"$name\": {", content)
        if pkg_section_start !== nothing
            # Find the next closing brace
            start_idx = pkg_section_start[end]
            depth = 1
            idx = start_idx + 1
            pkg_section_end = start_idx

            while idx <= length(content) && depth > 0
                if content[idx] == '{'
                    depth += 1
                elseif content[idx] == '}'
                    depth -= 1
                    if depth == 0
                        pkg_section_end = idx
                    end
                end
                idx += 1
            end

            pkg_section = content[start_idx:pkg_section_end]
            if !contains(pkg_section, "\"integrity\":")
                push!(
                    errors,
                    "Package '$name': missing 'integrity' field in Manifest.bazel.json",
                )
            elseif contains(pkg_section, "\"integrity\": \"\"")
                push!(
                    errors,
                    "Package '$name': 'integrity' field is empty in Manifest.bazel.json",
                )
            end
        end
    end

    return errors
end

function main()
    project_toml = ENV["RULES_JULIA_PKG_TEST_PROJECT_TOML"]
    manifest_toml = ENV["RULES_JULIA_PKG_TEST_MANIFEST_TOML"]
    manifest_bazel_json = get(ENV, "RULES_JULIA_PKG_TEST_MANIFEST_BAZEL_JSON", nothing)
    expected_version = VersionNumber(ENV["RULES_JULIA_PKG_TEST_JULIA_VERSION"])

    errors = String[]

    println("  Checking $(basename(manifest_toml)) against Project.toml (Julia $(VERSION))...")
    append!(errors, check_manifest_current(project_toml, manifest_toml, expected_version))

    if manifest_bazel_json !== nothing
        toml_packages = parse_manifest_toml(manifest_toml)
        println("  Verifying $(basename(manifest_bazel_json)) ($(length(toml_packages)) packages)...")
        append!(errors, check_lockfile_basic(manifest_bazel_json, toml_packages))
    end

    if isempty(errors)
        println("  OK")
        exit(0)
    end

    println("  Errors found:")
    for (i, error) in enumerate(errors)
        println("    $i. $error")
    end
    exit(1)
end

try
    main()
catch e
    println(stderr, "Fatal error:")
    showerror(stderr, e, catch_backtrace())
    println(stderr)
    exit(1)
end
